export const FETCH_COLLECTIONS_REQUEST = "FETCH_COLLECTIONS_REQUEST";
export const FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS";
export const FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTIONS_FAILURE";

export const FETCH_NFTS_REQUEST = "FETCH_NFTS_REQUEST";
export const FETCH_NFTS_SUCCESS = "FETCH_NFTS_SUCCESS";
export const FETCH_NFTS_FAILURE = "FETCH_NFTS_FAILURE";

// Action Types
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// ===== AUTH =====

export const LOGOUT = "LOGOUT";

// ===== COLLECTIONS =====

export const ADD_COLLECTION_REQUEST = "ADD_COLLECTION_REQUEST";
export const ADD_COLLECTION_SUCCESS = "ADD_COLLECTION_SUCCESS";
export const ADD_COLLECTION_FAILURE = "ADD_COLLECTION_FAILURE";

export const DELETE_COLLECTION_REQUEST = "DELETE_COLLECTION_REQUEST";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_FAILURE = "DELETE_COLLECTION_FAILURE";

// ===== NFTS =====

export const ADD_NFT_REQUEST = "ADD_NFT_REQUEST";
export const ADD_NFT_SUCCESS = "ADD_NFT_SUCCESS";
export const ADD_NFT_FAILURE = "ADD_NFT_FAILURE";

export const UPDATE_NFT_REQUEST = "UPDATE_NFT_REQUEST";
export const UPDATE_NFT_SUCCESS = "UPDATE_NFT_SUCCESS";
export const UPDATE_NFT_FAILURE = "UPDATE_NFT_FAILURE";

export const DELETE_NFT_REQUEST = "DELETE_NFT_REQUEST";
export const DELETE_NFT_SUCCESS = "DELETE_NFT_SUCCESS";
export const DELETE_NFT_FAILURE = "DELETE_NFT_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
