export const FETCH_COLLECTIONS_REQUEST = "FETCH_COLLECTIONS_REQUEST";
export const FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS";
export const FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTIONS_FAILURE";

export const FETCH_NFTS_REQUEST = "FETCH_NFTS_REQUEST";
export const FETCH_NFTS_SUCCESS = "FETCH_NFTS_SUCCESS";
export const FETCH_NFTS_FAILURE = "FETCH_NFTS_FAILURE";
